### ISSUE TITLE
[Servlet-003] : Adding GroupDocs.Annotation for Java 17.6.0 as an external Jar in the project raises exception

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-annotation/GroupDocs.Annotation-for-Java#15]
This issue was originally raised via forum thread:
https://forum.groupdocs.com/t/supported-documents-in-groupdocs-annotation-for-java-showcase-project/5132

When latest version of the API 17.6.0 is added in the project as an external Jar, showcase project raises exception.

**Comment by bobkovalex** [comment]
Please refer to new front-end examples for the fix:
https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-Java-Dropwizard
https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-Java-Spring
