### ISSUE TITLE
[Servlet-005] : Make front end responsive and mobile friendly

### ISSUE THREAD

**Issue by samicheemagroupdocs** [groupdocs-annotation/GroupDocs.Annotation-for-Java#19]
This issue was originally raised via forum thread:
https://forum.groupdocs.com/t/regarding-groupdocs-mobile-compatibility/5269

Currently the front end is not responsive, make it responsive and mobile friendly.

**Comment by bobkovalex** [comment]
This feature is now available in our new front-end examples::
https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-.NET-MVC
https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-.NET-WebForms
https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-Java-Dropwizard
https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-Java-Spring
