### ISSUE TITLE
Downloading is not working 

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-annotation/GroupDocs.Annotation-for-Java#44]
This issue is raised in https://forum.groupdocs.app/t/download-annotated-is-not-working/8896

In the Angular project, in the [annotation.service.ts](https://github.com/groupdocs-total/GroupDocs.Total-Angular/blob/master/libs/annotation/src/lib/annotation.service.ts) we have the following snippet of code:

```
getDownloadUrl(credentials: FileCredentials) {
    return this._config.getAnnotationApiEndpoint() + Api.DOWNLOAD_ANNOTATED + '/?path=' + credentials.guid;
}
```

This method calls a GET /downloadAnnotated?path=C:\exemple-file.docx
There are two problems, first the backslash cannot be used in browser URL, the second is this service is mapped differently in the backend, it is mapped as a POST method and the contract is different. See the [file](https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-Java/blob/master/Demos/Spring/src/main/java/com/groupdocs/ui/annotation/controller/AnnotationController.java).

```
@RequestMapping(method = RequestMethod.POST, value = "/downloadAnnotated", consumes = APPLICATION_JSON_VALUE)
public void downloadAnnotated(@RequestBody AnnotateDocumentRequest annotateDocumentRequest, HttpServletResponse response) {
  ...
}
```

**Comment by Pavel-Teplitsky** [comment]
Hi Atir,

Thank you for your request. I have checked this issue but unfortunately I can't reproduce it.
I have followed these steps:
1. Clone the repo ,or you can download it.
2. Set license path in the configuration.yml if you have.
3. Go to the  Demos\Spring folder
4. Open console and run mvn clean spring-boot:run 
![image](https://user-images.githubusercontent.com/2689279/130242550-39997a5c-8192-49aa-b042-ed9132572fd2.png)

5. When app in started open http://localhost:8080/annotation in you browser.
6. All works well.

If you faced with this issue after following my steps - please share additional info:
1. Browser.
2. Your OS
3. Issue screencast

Best regards.

**Comment by mcqueide** [comment]
> Hi Atir,
> 
> Thank you for your request. I have checked this issue but unfortunately I can't reproduce it.
> I have followed these steps:
> 
> 1. Clone the repo ,or you can download it.
> 2. Set license path in the configuration.yml if you have.
> 3. Go to the  Demos\Spring folder
> 4. Open console and run mvn clean spring-boot:run
>    ![image](https://user-images.githubusercontent.com/2689279/130242550-39997a5c-8192-49aa-b042-ed9132572fd2.png)
> 5. When app in started open http://localhost:8080/annotation in you browser.
> 6. All works well.
> 
> If you faced with this issue after following my steps - please share additional info:
> 
> 1. Browser.
> 2. Your OS
> 3. Issue screencast
> 
> Best regards.

Hello Pavel,

I have just tested this again following all the steps that you have suggested, and the problem still happens. When I click on the download button I get a 405 HTTP error. Just the backslash was fixed after Vladimir commit b7341bd8, this is the revision that I have checkout.

Additional info:
Browser: Google Chrome Version 92.0.4515.159 (Official Build) (64-bit)
OS: Windows 10
Screenshot: 
![image](https://user-images.githubusercontent.com/4754740/130275963-0330c799-002a-49f9-a9b6-d1edb6054262.png)
Git revision: b7341bd8

**Comment by vladimir-litvinchik** [comment]
@mcqueide 

Please try the latest version.

**Comment by mcqueide** [comment]
@vladimir-litvinchik

Thanks for your help, I updated the project, I made a test and the download button is working.
