### ISSUE TITLE
Java heap space error

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-annotation/GroupDocs.Annotation-for-Java#50]
This issue is raised in https://forum.groupdocs.com/t/java-lang-outofmemoryerror-java-heap-space/10166/3

Hi,
Please find the problematic file attached. You may need to have a look at this [video](https://drive.google.com/file/d/1AGONsdnwgie6aNRjCAd3K-iBv1kWC9HG/view?usp=sharing).
This [154601E2163 - C.pdf](https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-Java/files/7171723/154601E2163.-.C.pdf) file cannot be loaded in app and we get OutOfMemoryError. However, this file
[A3E021061A001 - 3.pdf](https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-Java/files/7171735/A3E021061A001.-.3.pdf) is successfully loaded. But after that if browser icon is pressed we again get same exception. 
Please take a look.
Thanks

**Comment by vitaliy-rezchikov** [comment]
Will have a look within ticket ANNOTATIONJAVA-1339

**Comment by mcqueide** [comment]
I did a simple test using PdfViewOptions instead of PngViewOptions and it works very fast and with a little memory consumption, but I couldn't render the file in the Viewer. Is there a way to work with it, instead of HtmlViewOptions or PngViewOptions?

**Comment by vladimir-litvinchik** [comment]
@mcqueide 

Can you please clarify if you're talking about GroupDocs.Viewer in your last comment?

**Comment by mcqueide** [comment]
Actually, this error is happening in GroupDocs.Viewer abd GroupDocs.Annotation.

**Comment by mcqueide** [comment]
@vladimir-litvinchik 

Actually, this error is happening in GroupDocs.Viewer abd GroupDocs.Annotation.

**Comment by vladimir-litvinchik** [comment]
@mcqueide 

Thank you for sharing the details, we'll investigate this issue and update you here.

**Comment by mcqueide** [comment]
@vladimir-litvinchik 

You're welcome, if you need any other detail let me know. :)

**Comment by vladimir-litvinchik** [comment]
@mcqueide 

I've reproduced this issue with Viewer and the files that you've attached. Please try increasing Java heap size by setting Maven options 
```bash
export MAVEN_OPTS="-Xmx4096m"
```
The [default heap size](https://blog.openj9.org/2020/04/30/default-java-maximum-heap-size-is-changed-for-java-8/) depends on the Java version that you're using. 

Let us know if you're still can reproduce this issue after setting Java heap size.

**Comment by mcqueide** [comment]
@vladimir-litvinchik 

I have already done this, to make all documents work I had to set it to for at least 6144m, but in a concurrency scenery where I was loading each file twice, with an interval of 3s between each request, I had to increase my Java heap size to 14GB.

**Comment by vladimir-litvinchik** [comment]
@vladimir-litvinchik 

Thanks for sharing the details. We're investigating why conversion requires so much memory to be allocated. In case of any updates well let you know here.

**Comment by mcqueide** [comment]
ok, thanks @vladimir-litvinchik

**Comment by mcqueide** [comment]
Hello, anyone has any updates on this issue, and does anyone have an idea about how much time will take to fix this issue?

**Comment by vladimir-litvinchik** [comment]
@mcqueide, the issue is still under investigation now. Unfortunately, there is no ETA at the moment.

**Comment by vladimir-litvinchik** [comment]
@mcqueide 

The memory allocations have been reduced in the latest version of GroupDocs.Annotation 21.7.2.
Please note that you probably still need to increase Java heap size as rendering the files you've attached (PDF files that contain large images.)
